# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jehyunpark.github.io" # the base hostname & protocol for your site
timezone: Asia/Seoul # https://en.wikipedia.org/wiki

# Site info
title: Jehyun Park
email: mepark333@gmail.com
description: Web Developer / Productive tool builder / Amateur soccer player

# Author info
twitter_username: mepark333
github_username:  jehyunpark
author:
  name:
    en: Jehyun Park
    kr: 박제현

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
